<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\EvaluasiQurban;
use Illuminate\Support\Facades\DB;

class EvaluasiQurban1446Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Data dari export Excel tahun 1446 H (19 data)
        $data = [
            // 1
            [
                'nama_shohibul' => 'Rizky Tri Putra',
                'jenis_hewan' => 'kambing',
                'sumber_info' => 'Spanduk/Banner',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'pihak_lain',
                'masukan_penyebaran_informasi' => 'Cukup jelas, informasi lengkap tertera di Banner. Narahubung fast respond (Pak Joko, Pak Imam dan Pak Jazuli)',
                'rating_pendaftaran' => 5,
                'saran_pendaftaran' => 'Cukup jelas, informasi lengkap tertera di Banner. Narahubung fast respond (Pak Joko, Pak Imam dan Pak Jazuli)',
                'rating_pelaksanaan' => 5,
                'saran_pelaksanaan' => 'Tidak ada, saya diberikan kesempatan langsung untuk menyembelih kurban dan diberikan arahan yg jelas olh vendornya.',
                'rating_distribusi' => 5,
                'saran_distribusi' => 'Distribusi kurban harus tepat sasaran. Dan pengkurban (wakilnya) kalo bisa diberikan fast akses pada saat pengambilan jatah kurban.',
                'rating_kualitas_hewan' => 5,
                'saran_kualitas_hewan' => null,
                'rencana_qurban' => 'mungkin',
                'hal_baik' => null,
                'hal_perbaikan' => null,
                'saran_tambahan' => null,
            ],
            // 2
            [
                'nama_shohibul' => 'Hana Fathiya dan Nasywa Zahra',
                'jenis_hewan' => 'sapi',
                'sumber_info' => 'Flyer',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'masjid',
                'masukan_penyebaran_informasi' => 'Spanduk, WA blast flier sudah merupakan metode yg tepat.',
                'rating_pendaftaran' => 5,
                'saran_pendaftaran' => 'Pendaftaran bisa melalui google form juga.',
                'rating_pelaksanaan' => 3,
                'saran_pelaksanaan' => 'Tempat penyembelihan terbatas, kurang profesional dalam mengatur penugasan dan kecepatan.',
                'rating_distribusi' => 2,
                'saran_distribusi' => 'Menumpuknya daging/tulang dan jeroan pada waktu sore dikarenakan terlambatnya pengerjaan pemotongan, pengulitan dan pencacahan.',
                'rating_kualitas_hewan' => 4,
                'saran_kualitas_hewan' => 'Sebaiknya hewan qurban 2 hari sebelum pemotongan harus sudah ada di lokasi pemotongan',
                'rencana_qurban' => 'mungkin',
                'hal_baik' => 'Penggunaan mesin harus ditambah. Operatornya juga harus ditambah.',
                'hal_perbaikan' => 'Penyedian vendor yg harus profesional.',
                'saran_tambahan' => 'Tidak ada',
            ],
            // 3
            [
                'nama_shohibul' => 'RADEN AYU IKA FITRIANA',
                'jenis_hewan' => 'sapi',
                'sumber_info' => 'WhatsApp',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'masjid',
                'masukan_penyebaran_informasi' => 'Sdh cukup baik',
                'rating_pendaftaran' => 5,
                'saran_pendaftaran' => 'Tidak ada',
                'rating_pelaksanaan' => 5,
                'saran_pelaksanaan' => 'Tidak ada',
                'rating_distribusi' => 5,
                'saran_distribusi' => 'Alhamdulillah pelaks.dan pendistribusian qurban th ini bagus lsg diantar ke peng-Qurban shg dagingnya fres....',
                'rating_kualitas_hewan' => 5,
                'saran_kualitas_hewan' => 'Alhamdulillah memuaskan',
                'rencana_qurban' => 'ya',
                'hal_baik' => 'Pendistribusian daging qurban tetap dipertahankan',
                'hal_perbaikan' => 'Tidak ada',
                'saran_tambahan' => 'Aangkah baiknya utk kedpnnya termasuk 2 kupon tambahannya lsg didistribusikan bsama daging qurban',
            ],
            // 4
            [
                'nama_shohibul' => 'Nanindya Ramadhina & muhamad dzaky',
                'jenis_hewan' => 'sapi',
                'sumber_info' => 'WhatsApp',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'masjid',
                'masukan_penyebaran_informasi' => 'Untuk spanduk lbh terang lg jd mudah dibaca',
                'rating_pendaftaran' => 5,
                'saran_pendaftaran' => 'Bagus',
                'rating_pelaksanaan' => 5,
                'saran_pelaksanaan' => 'Cukup baik',
                'rating_distribusi' => 4,
                'saran_distribusi' => 'Cukup baik',
                'rating_kualitas_hewan' => 4,
                'saran_kualitas_hewan' => 'Bagus',
                'rencana_qurban' => 'mungkin',
                'hal_baik' => 'Diluar proses penyembelihan ..yg lain bagus',
                'hal_perbaikan' => 'Cari tim jagalnya yg lbh baik',
                'saran_tambahan' => null,
            ],
            // 5
            [
                'nama_shohibul' => 'Meike Elvana Derianty',
                'jenis_hewan' => 'kambing',
                'sumber_info' => 'WhatsApp, Spanduk/Banner',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'masjid',
                'masukan_penyebaran_informasi' => 'Sudah bagus dan cukup jelas',
                'rating_pendaftaran' => 5,
                'saran_pendaftaran' => 'Sudah bagus dan cukup jelas',
                'rating_pelaksanaan' => 4,
                'saran_pelaksanaan' => 'Sebaiknya hewan yang belum dikurban, dipisahkan atau diberi tutupan terpal dari tempat penyembelihannya, agar tidak menyaksikan hewan yang sedang dikurban',
                'rating_distribusi' => 4,
                'saran_distribusi' => 'Untuk idul Adha selanjutnya, mungkin pengkurban bisa diberikan kesempatan untuk request bagian apa yang diinginkan',
                'rating_kualitas_hewan' => 4,
                'saran_kualitas_hewan' => 'Baik',
                'rencana_qurban' => 'ya',
                'hal_baik' => 'Respon cepat dan marketing',
                'hal_perbaikan' => 'Sudah saya tuliskan di pertanyaan sebelumnya',
                'saran_tambahan' => 'Sudah saya tuliskan di pertanyaan sebelumnya',
            ],
            // 6
            [
                'nama_shohibul' => 'Achmad Rafi',
                'jenis_hewan' => 'kambing',
                'sumber_info' => 'Spanduk/Banner',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'masjid',
                'masukan_penyebaran_informasi' => null,
                'rating_pendaftaran' => 4,
                'saran_pendaftaran' => 'Sudah baik',
                'rating_pelaksanaan' => 3,
                'saran_pelaksanaan' => 'Sudah baik',
                'rating_distribusi' => 4,
                'saran_distribusi' => 'Diberikan waktu/jadwal kapan sudah bisa dibagikan',
                'rating_kualitas_hewan' => 4,
                'saran_kualitas_hewan' => null,
                'rencana_qurban' => 'mungkin',
                'hal_baik' => null,
                'hal_perbaikan' => 'Jenis jenis ukuran hewannya dan harganya sehingga bisa menyesuaikan kesanggupan berkurban',
                'saran_tambahan' => null,
            ],
            // 7
            [
                'nama_shohibul' => 'Daffa M Adha Ar Rayan',
                'jenis_hewan' => 'sapi',
                'sumber_info' => 'WhatsApp, Spanduk/Banner',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'masjid',
                'masukan_penyebaran_informasi' => 'Sudah baik',
                'rating_pendaftaran' => 5,
                'saran_pendaftaran' => 'Sudah baik',
                'rating_pelaksanaan' => 5,
                'saran_pelaksanaan' => 'Sudah baik',
                'rating_distribusi' => 5,
                'saran_distribusi' => 'Sudah baik',
                'rating_kualitas_hewan' => 5,
                'saran_kualitas_hewan' => 'Sudah baik',
                'rencana_qurban' => 'ya',
                'hal_baik' => null,
                'hal_perbaikan' => null,
                'saran_tambahan' => null,
            ],
            // 8
            [
                'nama_shohibul' => 'Kharinda',
                'jenis_hewan' => 'kambing',
                'sumber_info' => 'Spanduk/Banner',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'masjid',
                'masukan_penyebaran_informasi' => 'Alhamdullilah saya wa pak jazuli, dijelaskan dengan sangat terkonsep bgmn kl mw berkurban di masjid. Hampir tdk jadi krn penjelasan awal, seperti hanya mengumpulkan dana saja kita ga tau prosesnya.',
                'rating_pendaftaran' => 5,
                'saran_pendaftaran' => 'Jelas , dipermudah, dan kupon diantar',
                'rating_pelaksanaan' => 5,
                'saran_pelaksanaan' => 'Sudah cukup baik',
                'rating_distribusi' => 5,
                'saran_distribusi' => 'Sudah baik',
                'rating_kualitas_hewan' => 5,
                'saran_kualitas_hewan' => 'Sudah baik',
                'rencana_qurban' => 'ya',
                'hal_baik' => 'Penjelasan pak jazuli agar bs diterapkan juga ke yg lain',
                'hal_perbaikan' => null,
                'saran_tambahan' => null,
            ],
            // 9
            [
                'nama_shohibul' => 'Almh. Sriwardani',
                'jenis_hewan' => 'sapi',
                'sumber_info' => 'Spanduk/Banner',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'masjid',
                'masukan_penyebaran_informasi' => 'kalau bisa H-1 bulan sudah disebarkan informasi harga kurban, agar lebih banyak peminat pengkurban yg mendaftar',
                'rating_pendaftaran' => 4,
                'saran_pendaftaran' => 'Kebetulan aku transfer dan Alhamdulillah CP yg tercantum fastrespons. terima kasih',
                'rating_pelaksanaan' => 4,
                'saran_pelaksanaan' => '-',
                'rating_distribusi' => 4,
                'saran_distribusi' => 'Penyebaran ke pengkurban sudah ok, daging yg didapatkan bersih full daging request tahun depan pengkurban bisa mendapatkan Iga walaupun cuma sedikit 🙏🏻. semoga ditahun selanjutnya untuk yg mendapatkan kupon bisa dicantumin waktu pengambilan ya, terima kasih',
                'rating_kualitas_hewan' => 4,
                'saran_kualitas_hewan' => 'Baik',
                'rencana_qurban' => 'ya',
                'hal_baik' => 'Overall ok',
                'hal_perbaikan' => 'Pendistribusian untuk yg punya kupon',
                'saran_tambahan' => '-',
            ],
            // 10
            [
                'nama_shohibul' => 'Musurifun Lajawa',
                'jenis_hewan' => 'kambing',
                'sumber_info' => 'WhatsApp',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'masjid',
                'masukan_penyebaran_informasi' => 'Spanduk kurban lebih awal lebih baik',
                'rating_pendaftaran' => 5,
                'saran_pendaftaran' => 'Ada baiknya juga melalui Qris',
                'rating_pelaksanaan' => 4,
                'saran_pelaksanaan' => 'Penawaran jasa vendor sedetail mungkin dan dituangkan dalam bentuk perjanjian yg komprehensif, sbg rujukan bila diperlukan (akuntabilitas)',
                'rating_distribusi' => 4,
                'saran_distribusi' => 'Sdh bagus, kalau bisa lebih awal',
                'rating_kualitas_hewan' => 5,
                'saran_kualitas_hewan' => 'Sangat baik',
                'rencana_qurban' => 'ya',
                'hal_baik' => 'Pelayanan informasi yg mudah dan updated',
                'hal_perbaikan' => 'Distribusi qurban yg lebih awal, sesuai jadwal - tdk sampai malam',
                'saran_tambahan' => '-',
            ],
            // 11
            [
                'nama_shohibul' => 'Indah Pasfitri DH',
                'jenis_hewan' => 'sapi',
                'sumber_info' => 'Brosur yang dikirim kerumah',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'pihak_lain',
                'masukan_penyebaran_informasi' => 'Sudah baik informasinya',
                'rating_pendaftaran' => 4,
                'saran_pendaftaran' => 'Sudah baik pelayanannya',
                'rating_pelaksanaan' => 4,
                'saran_pelaksanaan' => 'Sebaiknya untuk pemilik qurban masing2 sudah diberikan jadwal/waktu yang pasti untuk datang menyaksikan pelaksanaan penyembelihan qurbannya',
                'rating_distribusi' => 4,
                'saran_distribusi' => 'Sudah baik',
                'rating_kualitas_hewan' => 4,
                'saran_kualitas_hewan' => 'Sudah baik',
                'rencana_qurban' => 'mungkin',
                'hal_baik' => 'Sudah baik pelaksanaannya',
                'hal_perbaikan' => 'Cukup',
                'saran_tambahan' => 'Cukup',
            ],
            // 12
            [
                'nama_shohibul' => 'Sabili Rosyad Bin H M Yusuf Zarkonj',
                'jenis_hewan' => 'kambing',
                'sumber_info' => 'Spanduk/Banner',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'masjid',
                'masukan_penyebaran_informasi' => 'Tidak ada sudah cukup baik',
                'rating_pendaftaran' => 5,
                'saran_pendaftaran' => 'Sudah sangat baik',
                'rating_pelaksanaan' => 5,
                'saran_pelaksanaan' => 'Sudah sangat baik',
                'rating_distribusi' => 5,
                'saran_distribusi' => 'Sangat teratur dan sesuai jadwal',
                'rating_kualitas_hewan' => 5,
                'saran_kualitas_hewan' => null,
                'rencana_qurban' => 'ya',
                'hal_baik' => 'Komunikasi yang baik dan informasi yg jelas dari panitia',
                'hal_perbaikan' => 'Urutan pemotongan, mungkin diurutkan nomor atau jenis hewan kurban, salah satu saja',
                'saran_tambahan' => null,
            ],
            // 13 - INDAH PASFITRI DH (kedua)
            [
                'nama_shohibul' => 'Indah Pasfitri DH',
                'jenis_hewan' => 'sapi',
                'sumber_info' => 'Brosur yang dikirim kerumah',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'pihak_lain',
                'masukan_penyebaran_informasi' => 'Sudah baik',
                'rating_pendaftaran' => 4,
                'saran_pendaftaran' => 'Sudah baik',
                'rating_pelaksanaan' => 4,
                'saran_pelaksanaan' => 'Sebaiknya untuk pemilik hewan qurban diberitahukan terlebih dahulu jadwal/waktu yang pasti untuk datang menyaksikan penyembelihan qurbannya',
                'rating_distribusi' => 4,
                'saran_distribusi' => 'Sudah baik',
                'rating_kualitas_hewan' => 4,
                'saran_kualitas_hewan' => 'Sudah baik',
                'rencana_qurban' => 'mungkin',
                'hal_baik' => 'Sudah cukup baik',
                'hal_perbaikan' => 'Sudah cukup baik',
                'saran_tambahan' => 'Cukup',
            ],
            // 14
            [
                'nama_shohibul' => 'Both Soemarsono',
                'jenis_hewan' => 'sapi',
                'sumber_info' => 'dari info di masjid',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'masjid',
                'masukan_penyebaran_informasi' => 'cukup effektif bagi yg minat berqurban',
                'rating_pendaftaran' => 5,
                'saran_pendaftaran' => 'cukup effektif dari informasi flayer',
                'rating_pelaksanaan' => 3,
                'saran_pelaksanaan' => 'agar bisa dipercepat pencacahan agar antrian tidak sampai malam',
                'rating_distribusi' => 4,
                'saran_distribusi' => 'dipercepat dan diusahan sebelum magrib selesai',
                'rating_kualitas_hewan' => 5,
                'saran_kualitas_hewan' => 'sudah baik',
                'rencana_qurban' => 'ya',
                'hal_baik' => 'Team panitia solid',
                'hal_perbaikan' => 'tambah petugas utamakan regenerasi',
                'saran_tambahan' => 'tingkatkan kebersamaan panitia',
            ],
            // 15
            [
                'nama_shohibul' => 'Rheznandya Arkaputra Azis',
                'jenis_hewan' => 'kambing',
                'sumber_info' => 'WhatsApp, Spanduk/Banner',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'masjid',
                'masukan_penyebaran_informasi' => null,
                'rating_pendaftaran' => 5,
                'saran_pendaftaran' => '-',
                'rating_pelaksanaan' => 5,
                'saran_pelaksanaan' => '-',
                'rating_distribusi' => 5,
                'saran_distribusi' => '-',
                'rating_kualitas_hewan' => 5,
                'saran_kualitas_hewan' => null,
                'rencana_qurban' => 'ya',
                'hal_baik' => 'Sistem pendaftaran dan pembelian hewan kurban sudah sangat baik.',
                'hal_perbaikan' => null,
                'saran_tambahan' => null,
            ],
            // 16
            [
                'nama_shohibul' => 'Arianti Dwitya Ichsani',
                'jenis_hewan' => 'sapi',
                'sumber_info' => 'Flyer, Spanduk/Banner',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'masjid',
                'masukan_penyebaran_informasi' => 'Sudah baik dan informatif',
                'rating_pendaftaran' => 5,
                'saran_pendaftaran' => 'Sudah baik dan fast response',
                'rating_pelaksanaan' => 5,
                'saran_pelaksanaan' => 'bagus dan rapi',
                'rating_distribusi' => 5,
                'saran_distribusi' => 'sudah bagus',
                'rating_kualitas_hewan' => 5,
                'saran_kualitas_hewan' => 'bagus',
                'rencana_qurban' => 'ya',
                'hal_baik' => '-',
                'hal_perbaikan' => '-',
                'saran_tambahan' => '-',
            ],
            // 17
            [
                'nama_shohibul' => 'Yan Leo Nel',
                'jenis_hewan' => 'sapi',
                'sumber_info' => 'Flyer, Spanduk/Banner',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'masjid',
                'masukan_penyebaran_informasi' => 'Sangat baik dan sangat jelas informasinya',
                'rating_pendaftaran' => 5,
                'saran_pendaftaran' => 'Prosesnya cepat dan lancar',
                'rating_pelaksanaan' => 5,
                'saran_pelaksanaan' => 'Sangat baik dan berjalan dengan lancar',
                'rating_distribusi' => 5,
                'saran_distribusi' => 'Baik, lancar dan diterima yang berhak',
                'rating_kualitas_hewan' => 5,
                'saran_kualitas_hewan' => 'Sehat dan gemuk',
                'rencana_qurban' => 'ya',
                'hal_baik' => 'Pelaksanaan yang sudah berjalan baik tetap dipertahankan',
                'hal_perbaikan' => null,
                'saran_tambahan' => null,
            ],
            // 18
            [
                'nama_shohibul' => 'Alifa Nindita Larasati',
                'jenis_hewan' => 'sapi',
                'sumber_info' => 'WhatsApp, Flyer, Spanduk/Banner',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'masjid',
                'masukan_penyebaran_informasi' => 'sudah sangat informatif. Panitia jg cepat dalam merespon pertanyaan',
                'rating_pendaftaran' => 5,
                'saran_pendaftaran' => 'pelayanan sudah sangat baik',
                'rating_pelaksanaan' => 5,
                'saran_pelaksanaan' => 'pelaksanaan sudah bagus',
                'rating_distribusi' => 5,
                'saran_distribusi' => 'distribusi sudah lancar & bagus',
                'rating_kualitas_hewan' => 5,
                'saran_kualitas_hewan' => 'bagi saya yang penting memenuhi syarat sah untuk qurban. Saya sangat yakin & percaya bapak2 panitia pasti lebih paham hal tersebut.',
                'rencana_qurban' => 'mungkin',
                'hal_baik' => 'Semua yang diupayakan panitia sudah bagus.',
                'hal_perbaikan' => 'sudah bagus',
                'saran_tambahan' => '-',
            ],
            // 19 - INDAH PASFITRI (ketiga)
            [
                'nama_shohibul' => 'Indah Pasfitri',
                'jenis_hewan' => 'sapi',
                'sumber_info' => 'Brosur dikirim kerumah',
                'sumber_info_lainnya' => null,
                'tempat_qurban' => 'pihak_lain',
                'masukan_penyebaran_informasi' => 'Sudah baik',
                'rating_pendaftaran' => 4,
                'saran_pendaftaran' => 'Sudah baik',
                'rating_pelaksanaan' => 4,
                'saran_pelaksanaan' => 'Mohon lebih bisa diatur jadwal kehadiran pemilik hewan qurban untuk menyaksikan saat penyembelihan hewan qurbannya',
                'rating_distribusi' => 4,
                'saran_distribusi' => 'Sudah baik',
                'rating_kualitas_hewan' => 4,
                'saran_kualitas_hewan' => 'Baik kwalitasnya',
                'rencana_qurban' => 'mungkin',
                'hal_baik' => 'Cukup',
                'hal_perbaikan' => 'Cukup',
                'saran_tambahan' => 'Cukup',
            ],
        ];

        // Insert data dengan tahun 1446 H
        foreach ($data as $item) {
            EvaluasiQurban::create(array_merge($item, [
                'tahun_hijriah' => '1446 H',
                'masjid_code' => 'mrj',
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('Seeder data evaluasi qurban 1446 H berhasil dijalankan. Total: ' . count($data) . ' data.');
    }
}