<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KhutbahJumatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // JANUARI 2026
            [
                'khatib' => 'Ustadz Miftah Abdillah, S.Ag',
                'tema' => null,
                'tanggal' => 'Jumat, 2 Januari 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-01-02',
                'keterangan' => 'PIC: Pak Hamdi | Konfirmasi: Ok',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Dr Abdul Rahman Rojali Lc M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 9 Januari 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-01-09',
                'keterangan' => 'PIC: Pak Hamdi | Konfirmasi: Ok',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Imam Syuhada',
                'tema' => null,
                'tanggal' => 'Jumat, 16 Januari 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-01-16',
                'keterangan' => 'PIC: Pak Indra | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Nur Achmad',
                'tema' => null,
                'tanggal' => 'Jumat, 23 Januari 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-01-23',
                'keterangan' => 'PIC: Pak Hamdi | Konfirmasi: Ok',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustad Mujiburohman, S.Th.I, Lc, M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 30 Januari 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-01-30',
                'keterangan' => 'PIC: Pak Hamdi | Konfirmasi: Ok',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // FEBRUARI 2026
            [
                'khatib' => 'Ustadz Dr Rosyidin Effendi M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 6 Februari 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-02-06',
                'keterangan' => 'PIC: Pak Hafri | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Bambang Syuhada',
                'tema' => null,
                'tanggal' => 'Jumat, 13 Februari 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-02-13',
                'keterangan' => 'PIC: Pak Hafri | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Dr Bambang Irawan M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 20 Februari 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-02-20',
                'keterangan' => 'PIC: Pak Hafri | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Umar Farouq Lc M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 27 Februari 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-02-27',
                'keterangan' => 'PIC: Pak Hafri | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // MARET 2026
            [
                'khatib' => 'Ustadz Kholik Ramdan Mahesa M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 6 Maret 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-03-06',
                'keterangan' => 'PIC: Pak Ari | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Sulaiman LC',
                'tema' => null,
                'tanggal' => 'Jumat, 13 Maret 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-03-13',
                'keterangan' => 'PIC: Pak Ari | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Dr Abdur Rauf M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 20 Maret 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-03-20',
                'keterangan' => 'PIC: Pak Ari | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Canra Krisna Jaya',
                'tema' => null,
                'tanggal' => 'Jumat, 27 Maret 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-03-27',
                'keterangan' => 'PIC: Pak Ari | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // APRIL 2026
            [
                'khatib' => 'Ustadz M. Hari Sanusi',
                'tema' => null,
                'tanggal' => 'Jumat, 3 April 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-04-03',
                'keterangan' => 'PIC: Pak Indra | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Dr Ahmad Fatoni M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 10 April 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-04-10',
                'keterangan' => 'PIC: Pak Indra | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Teguh Budiarto',
                'tema' => null,
                'tanggal' => 'Jumat, 17 April 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-04-17',
                'keterangan' => 'PIC: Pak Indra | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Drs. H. Ali Rosyidin M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 24 April 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-04-24',
                'keterangan' => 'PIC: Pak Indra | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // MEI 2026
            [
                'khatib' => 'Ustadz Dr Andian Parlindungan M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 1 Mei 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-05-01',
                'keterangan' => 'PIC: Pak Heru | Konfirmasi: Ok',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Salam',
                'tema' => null,
                'tanggal' => 'Jumat, 8 Mei 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-05-08',
                'keterangan' => 'PIC: Pak Heru | Konfirmasi: Ok',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Abdul Muis Sobri M.Kom',
                'tema' => null,
                'tanggal' => 'Jumat, 15 Mei 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-05-15',
                'keterangan' => 'PIC: Pak Heru | Konfirmasi: Ok',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Burhan Ahmad Fauzan',
                'tema' => null,
                'tanggal' => 'Jumat, 22 Mei 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-05-22',
                'keterangan' => 'PIC: Pak Heru | Konfirmasi: Ok',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Muhammad Nuhri',
                'tema' => null,
                'tanggal' => 'Jumat, 29 Mei 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-05-29',
                'keterangan' => 'PIC: Pak Heru | Konfirmasi: Ok',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // JUNI 2026
            [
                'khatib' => 'Ustadz Zulfa Hendra',
                'tema' => null,
                'tanggal' => 'Jumat, 5 Juni 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-06-05',
                'keterangan' => 'PIC: Mas Pur | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Afdholi',
                'tema' => null,
                'tanggal' => 'Jumat, 12 Juni 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-06-12',
                'keterangan' => 'PIC: Mas Pur | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz H Maulana Firdaus M AG',
                'tema' => null,
                'tanggal' => 'Jumat, 19 Juni 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-06-19',
                'keterangan' => 'PIC: Pak Hafri | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Arman Rahman',
                'tema' => null,
                'tanggal' => 'Jumat, 26 Juni 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-06-26',
                'keterangan' => 'PIC: Mas Pur | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // JULI 2026
            [
                'khatib' => 'Ustadz Dr. Ade Yusuf Mujaddid M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 3 Juli 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-07-03',
                'keterangan' => 'PIC: Pak Hafri | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Agus Purwanto, Lc, M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 10 Juli 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-07-10',
                'keterangan' => 'PIC: Pak Hafri | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Abdul Rozik',
                'tema' => null,
                'tanggal' => 'Jumat, 17 Juli 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-07-17',
                'keterangan' => 'PIC: Pak Hafri | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Zetri A Fatullah',
                'tema' => null,
                'tanggal' => 'Jumat, 24 Juli 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-07-24',
                'keterangan' => 'PIC: Pak Hafri | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Adi Susanto',
                'tema' => null,
                'tanggal' => 'Jumat, 31 Juli 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-07-31',
                'keterangan' => 'PIC: Pak Hafri | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // AGUSTUS 2026
            [
                'khatib' => 'Ustadz Suparlan',
                'tema' => null,
                'tanggal' => 'Jumat, 7 Agustus 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-08-07',
                'keterangan' => 'PIC: Pak Hamdi | Konfirmasi: Ok aja orng dalam',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz H. Dr Fudhoil Rahman M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 14 Agustus 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-08-14',
                'keterangan' => 'PIC: Pak Hamdi | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz H. Muhammad Shaufi, M.Pd.I, M.A., M. CB',
                'tema' => null,
                'tanggal' => 'Jumat, 21 Agustus 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-08-21',
                'keterangan' => 'PIC: Pak Hamdi | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Dr Rahmat Hidayat Lubis Lc M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 28 Agustus 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-08-28',
                'keterangan' => 'PIC: Pak Hamdi | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // SEPTEMBER 2026
            [
                'khatib' => 'Ustadz Isa Ansori',
                'tema' => null,
                'tanggal' => 'Jumat, 4 September 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-09-04',
                'keterangan' => 'PIC: Pak Ari | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Hasbi Abi Zaky',
                'tema' => null,
                'tanggal' => 'Jumat, 11 September 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-09-11',
                'keterangan' => 'PIC: Pak Ari | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Mukhtar Ibnu',
                'tema' => null,
                'tanggal' => 'Jumat, 18 September 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-09-18',
                'keterangan' => 'PIC: Pak Ari | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Dr. Suheri Mukti',
                'tema' => null,
                'tanggal' => 'Jumat, 25 September 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-09-25',
                'keterangan' => 'PIC: Pak Ari | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // OKTOBER 2026
            [
                'khatib' => 'Ustadz Rido Abu H',
                'tema' => null,
                'tanggal' => 'Jumat, 2 Oktober 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-10-02',
                'keterangan' => 'PIC: Pak Indra | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Iwan Santoso',
                'tema' => null,
                'tanggal' => 'Jumat, 9 Oktober 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-10-09',
                'keterangan' => 'PIC: Pak Indra | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Ibnu Hajar Mahbub',
                'tema' => null,
                'tanggal' => 'Jumat, 16 Oktober 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-10-16',
                'keterangan' => 'PIC: Pak Indra | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Zakaria Lubis M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 23 Oktober 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-10-23',
                'keterangan' => 'PIC: Pak Indra | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Ahmad Nawawi',
                'tema' => null,
                'tanggal' => 'Jumat, 30 Oktober 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-10-30',
                'keterangan' => 'PIC: Pak Indra | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // NOVEMBER 2026
            [
                'khatib' => 'Ustadz M. Fikri Hasbi',
                'tema' => null,
                'tanggal' => 'Jumat, 6 November 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-11-06',
                'keterangan' => 'PIC: Pak Heru | Konfirmasi: Ok',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Muntohar',
                'tema' => null,
                'tanggal' => 'Jumat, 13 November 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-11-13',
                'keterangan' => 'PIC: Pak Heru | Konfirmasi: Ok',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Mansyur Adnan S.Ag',
                'tema' => null,
                'tanggal' => 'Jumat, 20 November 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-11-20',
                'keterangan' => 'PIC: Pak Heru | Konfirmasi: Ok',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Buchari Muslim',
                'tema' => null,
                'tanggal' => 'Jumat, 27 November 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-11-27',
                'keterangan' => 'PIC: Pak Heru | Konfirmasi: Ok',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // DESEMBER 2026
            [
                'khatib' => 'Ustadz Hasanuddin, M.Pd I',
                'tema' => null,
                'tanggal' => 'Jumat, 4 Desember 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-12-04',
                'keterangan' => 'PIC: Mas Pur | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Dr. Syukron Makmun, M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 11 Desember 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-12-11',
                'keterangan' => 'PIC: Mas Pur | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Muchlisin',
                'tema' => null,
                'tanggal' => 'Jumat, 18 Desember 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-12-18',
                'keterangan' => 'PIC: Mas Pur | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'khatib' => 'Ustadz Dr. Ilham Wahyudi, M.A.',
                'tema' => null,
                'tanggal' => 'Jumat, 25 Desember 2026',
                'jam' => '12:00 WIB',
                'tanggal_asli' => '2026-12-25',
                'keterangan' => 'PIC: Mas Pur | Konfirmasi: OK',
                'is_active' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('khutbah_jumat')->insert($data);
    }
}
