
<section class="my-8 rounded-2xl bg-base-100 border border-base-300 p-4 shadow-sm sm:p-5">
<div class="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div class="min-w-0"><h2 class="font-bold text-xl">Penyaluran dan penerima manfaat</h2><p class="text-sm mt-2 text-base-content/65">Total operasional bukan tambahan pengeluaran finansial. Agregat tertaut hanya menghitung realisasi utuh dalam cakupan Dana.</p></div><div class="flex shrink-0 flex-wrap gap-2"><span class="badge badge-outline">{{ $report['distributions']['distribution_events'] }} penyaluran</span><span class="badge badge-outline">{{ $report['distributions']['unique_beneficiaries'] }} penerima unik</span></div></div>
<a class="btn btn-outline btn-sm mb-4" href="{{ route('financial-v2.distributions.index', ['entity' => $entity->id, 'program_id' => $report['filters']['program_id'] ?? null]) }}">Lihat periode / kelola penyaluran</a>
<div class="grid gap-3 sm:grid-cols-2">
@forelse($report['distributions']['programs'] as $row)<article class="flex h-full min-w-0 flex-col rounded-xl bg-base-200 p-4"><h3 class="break-words font-semibold">{{ $row['program_name'] }}</h3><p class="mt-2 text-sm text-base-content/65">{{ $row['distribution_events'] }} kejadian · {{ $row['unique_beneficiaries'] }} penerima unik</p><dl class="mt-auto grid gap-1 pt-3 text-sm"><div class="flex flex-wrap justify-between gap-2"><dt>Total operasional</dt><dd class="font-semibold">Rp{{ number_format((float) $row['operational_total'], 2, ',', '.') }}</dd></div><div class="flex flex-wrap justify-between gap-2"><dt>Actual tertaut</dt><dd class="font-semibold">Rp{{ number_format((float) $row['actual_amount'], 2, ',', '.') }}</dd></div></dl></article>
@empty<p class="text-sm">Belum ada penyaluran pada periode ini.</p>
@endforelse</div>
<div class="grid gap-3 sm:grid-cols-2 mt-4">
@foreach($report['distributions']['events'] as $row)<article class="flex h-full min-w-0 flex-col rounded-xl border border-base-300 p-4 text-sm"><p class="break-words font-semibold">{{ $row['program_name'] }} · {{ $row['period'] }}</p><p class="mt-2 text-base-content/65">{{ $row['recipient_count'] }} penerima</p><div class="mt-2 flex flex-wrap gap-2"><span class="badge badge-ghost badge-sm">{{ $row['operational_status'] }}</span><span class="badge badge-ghost badge-sm">{{ $row['financial_status'] }}</span></div>
<a class="link mt-auto pt-3" href="{{ route('financial-v2.distributions.show', ['entity' => $entity->id, 'distribution' => $row['distribution_id']]) }}">Rincian penyaluran</a></article>
@endforeach</div>
<div class="mt-6 border-t border-base-200 pt-5"><h3 class="font-semibold">Sebaran RT/RW</h3><div class="mt-3 grid auto-rows-fr gap-3 sm:grid-cols-2 lg:grid-cols-3">@forelse($report['distributions']['regions'] as $region)<article class="flex min-w-0 items-start justify-between gap-3 rounded-xl border border-base-300 bg-base-100 p-3 text-sm"><div class="min-w-0"><p class="font-semibold">RT {{ $region['rt'] ?: '—' }} / RW {{ $region['rw'] ?: '—' }}</p><p class="mt-1 break-words text-xs text-base-content/60">{{ $region['coordinator'] ?: 'Tanpa koordinator' }}</p></div><span class="badge badge-primary badge-outline shrink-0">{{ $region['recipient_count'] }} penerima</span></article>@empty<p class="text-sm text-base-content/60">Belum ada sebaran.</p>@endforelse</div></div>
</section>
