<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>Detail Penyaluran ZISWAF</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen overflow-x-hidden bg-slate-50 text-slate-900">
@php
$rp=static fn($n)=>'Rp'.number_format((float)$n,0,',','.');
$transaction=$distribution->realization?->transaction;
$actual=$reported['actual_amount']??'0.00';
$snapshot=static fn($item,$key,$fallback='—')=>filled(data_get($item->effective_identity_snapshot,$key))?data_get($item->effective_identity_snapshot,$key):$fallback;
@endphp
<header class="border-b border-emerald-900 bg-emerald-950 text-white"><div class="mx-auto max-w-7xl px-4 py-7 sm:px-6"><nav aria-label="Breadcrumb" class="text-xs text-emerald-200"><a class="rounded focus:outline-none focus:ring-2 focus:ring-white" href="{{ route('internal.ziswaf.dashboard') }}">Ringkasan ZISWAF</a><span class="mx-2">/</span><span>Detail penyaluran</span></nav><div class="mt-4 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div class="min-w-0"><p class="text-xs font-bold uppercase tracking-[.2em] text-emerald-300">{{ $distribution->program->name }}</p><h1 class="mt-2 break-words text-2xl font-bold sm:text-3xl">{{ $distribution->title }}</h1><p class="mt-2 text-sm text-emerald-100">{{ $distribution->period_label }} · {{ $distribution->starts_on->format('d/m/Y') }}–{{ $distribution->ends_on->format('d/m/Y') }}</p></div><div class="flex flex-wrap gap-2"><span class="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">Operasional: {{ strtoupper($distribution->status) }}</span><span class="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">Finansial: {{ strtoupper($transaction?->status??'belum tertaut') }}</span></div></div></div></header>
<main class="mx-auto max-w-7xl space-y-7 px-4 py-6 sm:px-6">
<a class="inline-flex min-h-10 items-center rounded-lg border border-slate-300 bg-white px-4 text-sm font-bold text-emerald-800 shadow-sm focus:outline-none focus:ring-2 focus:ring-emerald-600" href="{{ route('internal.ziswaf.dashboard', request()->only(['from','through','fund_id','type','status'])) }}#penyaluran">← Kembali ke daftar penyaluran</a>
<section aria-label="Ringkasan realisasi" class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
@foreach([['Penerima',$totalRecipients.' orang','Detail unik pada kegiatan ini','text-slate-900'],['Total rincian bantuan',$operationalTotal,'Jumlah nominal seluruh penerima','text-emerald-700'],['Total operasional',$reported['operational_total']??$operationalTotal,'Agregat operasional, bukan expense tambahan','text-amber-700'],['Actual tertaut',$actual,$transaction?'Expense posted yang lolos rekonsiliasi':'Belum ada transaksi valid','text-emerald-800']] as [$label,$value,$hint,$tone])
<article class="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-semibold text-slate-500">{{ $label }}</p><p class="mt-2 break-words text-2xl font-extrabold tracking-tight {{ $tone }}">{{ is_numeric($value)?$rp($value):$value }}</p><p class="mt-2 text-xs leading-5 text-slate-500">{{ $hint }}</p></article>@endforeach
</section>
<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><h2 class="text-lg font-bold">Transaksi Keuangan Tertaut</h2><p class="mt-1 text-sm text-slate-500">Informasi ini terpisah dari rincian operasional penerima.</p></div>@if($transaction)<a class="inline-flex min-h-10 items-center justify-center rounded-lg border border-emerald-700 px-4 text-sm font-bold text-emerald-800 focus:ring-2 focus:ring-emerald-600" href="{{ route('internal.ziswaf.transactions.show',$transaction) }}">Buka detail transaksi</a>@endif</div>
@if($transaction)<dl class="mt-5 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-slate-500">Tanggal</dt><dd class="mt-1 font-semibold">{{ $transaction->business_date->format('d/m/Y') }}</dd></div><div><dt class="text-slate-500">Nominal transaksi</dt><dd class="mt-1 font-semibold">{{ $rp($transaction->gross_amount) }}</dd></div><div><dt class="text-slate-500">Fund</dt><dd class="mt-1 font-semibold">{{ $transaction->splits->pluck('fund.name')->filter()->unique()->join(', ')?:'—' }}</dd></div><div><dt class="text-slate-500">Status</dt><dd class="mt-1 font-semibold uppercase">{{ $transaction->status }}</dd></div></dl>@if(!\App\Domain\FinancialV2\DecimalAmount::equals($operationalTotal,(string)$transaction->gross_amount))<p class="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Total rincian penerima berbeda dari nominal transaksi tertaut. Nilai ditampilkan sesuai sumber masing-masing dan tidak disamakan secara otomatis.</p>@endif
@else<p class="mt-5 rounded-xl bg-slate-100 p-4 text-sm text-slate-600">Realisasi ini belum mempunyai transaksi Financial V2 tertaut.</p>@endif</section>
<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><h2 class="text-xl font-bold">Daftar Penerima Manfaat</h2><p class="mt-1 text-sm text-slate-500">{{ $filteredCount }} penerima · total dalam hasil {{ $rp($filteredTotal) }}</p></div><form method="get" class="grid gap-2 sm:grid-cols-4"><label class="text-xs font-semibold text-slate-600">Cari nama<input name="q" value="{{ $input['q']??'' }}" class="mt-1 min-h-11 w-full rounded-lg border-slate-300 focus:border-emerald-600 focus:ring-emerald-600" placeholder="Nama penerima"></label><label class="text-xs font-semibold text-slate-600">RT<input name="rt" value="{{ $input['rt']??'' }}" class="mt-1 min-h-11 w-full rounded-lg border-slate-300 focus:border-emerald-600 focus:ring-emerald-600"></label><label class="text-xs font-semibold text-slate-600">RW<input name="rw" value="{{ $input['rw']??'' }}" class="mt-1 min-h-11 w-full rounded-lg border-slate-300 focus:border-emerald-600 focus:ring-emerald-600"></label><div class="flex items-end gap-2"><button class="min-h-11 rounded-lg bg-emerald-700 px-4 text-sm font-bold text-white focus:ring-2 focus:ring-emerald-600">Cari</button><a class="inline-flex min-h-11 items-center rounded-lg border px-3 text-sm font-semibold" href="{{ route('internal.ziswaf.distributions.show',$distribution) }}">Reset</a></div></form></div>
<div class="mt-6 space-y-5">
@forelse($pageGroups as $groupKey => $groupItems)
@php $group=$groups->get($groupKey); @endphp
<article class="overflow-hidden rounded-2xl border border-emerald-100 bg-white shadow-sm">
<header class="border-b border-emerald-100 bg-emerald-50/70 px-4 py-4 sm:px-5"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 class="font-bold text-emerald-950">{{ filled($group['rt'])||filled($group['rw'])?'RT '.($group['rt']?:'—').' / RW '.($group['rw']?:'—'):'Wilayah belum tercatat' }}</h3><p class="mt-1 text-sm text-emerald-800">Koordinator: {{ $group['coordinator']?:'Belum tercatat' }}</p></div><div class="flex flex-wrap gap-2 text-xs font-bold"><span class="rounded-full bg-white px-3 py-1.5 text-emerald-800 shadow-sm">{{ $group['recipient_count'] }} penerima</span><span class="rounded-full bg-amber-50 px-3 py-1.5 text-amber-800">Subtotal {{ $rp($group['total']) }}</span></div></div></header>
<x-horizontal-scroll-table><table class="w-full min-w-[680px] text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3">No</th><th class="px-4 py-3">Nama Penerima</th><th class="px-4 py-3">Kategori</th><th class="px-4 py-3 text-right">Nominal Bantuan</th><th class="px-4 py-3">Catatan</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($groupItems as $item)<tr class="hover:bg-emerald-50/40"><td class="px-4 py-3 text-slate-500">{{ $items->firstItem()+$items->getCollection()->search(fn($candidate)=>$candidate->id===$item->id) }}</td><td class="px-4 py-3 font-semibold">{{ $snapshot($item,'display_name') }}</td><td class="px-4 py-3">{{ \Illuminate\Support\Str::of($snapshot($item,'beneficiary_type','Belum ditentukan'))->replace('_',' ')->lower()->title() }}</td><td class="whitespace-nowrap px-4 py-3 text-right font-mono font-bold text-emerald-800">{{ $rp($item->amount) }}</td><td class="max-w-xs break-words px-4 py-3 text-slate-600">{{ $item->notes?:'—' }}</td></tr>@endforeach</tbody></table></x-horizontal-scroll-table>
@if($group['recipient_count']>$groupItems->count())<p class="border-t border-emerald-100 bg-emerald-50/30 px-4 py-2 text-xs text-emerald-800">Kelompok ini berlanjut pada halaman lain; jumlah dan subtotal di atas mencakup seluruh hasil filter.</p>@endif
</article>
@empty<div class="rounded-xl bg-slate-50 px-4 py-12 text-center text-slate-500">Tidak ada penerima yang sesuai dengan pencarian.</div>@endforelse
</div><div class="mt-5">{{ $items->links() }}</div></section>
<p class="pb-8 text-center text-xs text-slate-500">Identitas menampilkan atribusi efektif terbaru. Snapshot asli saat penyaluran dibuat tetap dipertahankan dalam riwayat audit.</p>
</main></body></html>
