@extends('masjid.master-guest')

@section('title', 'Laporan Pengelolaan Dana ZISWAF')

@php $rupiah = static fn (string $amount): string => 'Rp'.number_format((float) $amount, 0, ',', '.'); @endphp

@section('content')
    <main class="min-h-screen bg-gradient-to-b from-emerald-50 via-white to-amber-50 px-4 py-8 sm:px-6 sm:py-12">
        <div class="mx-auto max-w-6xl">
            <header class="overflow-hidden rounded-[2rem] bg-emerald-950 px-6 py-10 text-white shadow-xl sm:px-10 sm:py-14"><p class="text-xs font-bold uppercase tracking-[.22em] text-emerald-200">{{ $report['entity']['name'] }}</p><h1 class="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">Laporan Pengelolaan Dana ZISWAF</h1><p class="mt-3 max-w-2xl text-emerald-100">Transparansi dana amanah untuk jamaah · Periode {{ $report['period']['from'] }} — {{ $report['period']['through'] }}</p></header>
            <form class="mt-6 grid gap-3 rounded-2xl border border-emerald-100 bg-white p-4 shadow-sm sm:grid-cols-[1fr_1fr_auto]" method="GET" action="{{ route('public.ziswaf-v2.index') }}"><label class="text-sm font-semibold text-slate-700">Tanggal mulai<input class="mt-1 block w-full rounded-xl border-slate-300" type="date" name="from" value="{{ $report['period']['from'] }}"></label><label class="text-sm font-semibold text-slate-700">Tanggal akhir<input class="mt-1 block w-full rounded-xl border-slate-300" type="date" name="through" value="{{ $report['period']['through'] }}"></label><button class="mt-6 rounded-xl bg-emerald-700 px-5 py-2 text-sm font-bold text-white hover:bg-emerald-800">Terapkan</button></form>
            <section class="mt-10"><div class="mb-4 flex items-center gap-2"><span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold tracking-wide text-emerald-800">ACTUAL · POSTED</span><p class="text-sm text-slate-500">Bersumber dari pembukuan Financial V2</p></div><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach ([['Saldo Awal', $report['summary']['opening_balance'], 'text-slate-900'], ['Total Penerimaan', $report['summary']['receipts'], 'text-emerald-700'], ['Total Pengeluaran', $report['summary']['expenses'], 'text-rose-700'], ['Saldo Akhir', $report['summary']['closing_balance'], 'text-emerald-800']] as [$label, $amount, $color])<article class="rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ $label }}</p><p class="mt-3 text-2xl font-bold tracking-tight {{ $color }}">{{ $rupiah($amount) }}</p></article>@endforeach</div></section>
            <section class="mt-12"><p class="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">Dana per Fund</p><h2 class="mt-1 text-2xl font-bold text-emerald-950">Ringkasan Dana Amanah</h2><div class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">@forelse($report['funds'] as $fund)<article class="rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm"><p class="font-bold text-emerald-950">{{ $fund['name'] }}</p><p class="mt-1 text-xs text-slate-500">{{ $fund['code'] }}</p><dl class="mt-5 space-y-2 text-sm"><div class="flex justify-between gap-4"><dt class="text-slate-500">Penerimaan</dt><dd class="font-semibold text-emerald-700">{{ $rupiah($fund['receipts']) }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Pengeluaran</dt><dd class="font-semibold text-rose-700">{{ $rupiah($fund['expenses']) }}</dd></div><div class="flex justify-between gap-4 border-t border-slate-100 pt-3"><dt class="font-semibold text-slate-700">Saldo Dana</dt><dd class="font-bold text-slate-900">{{ $rupiah($fund['fund_balance']) }}</dd></div></dl></article>@empty<article class="rounded-2xl border border-emerald-100 bg-white p-5 text-slate-500 md:col-span-2 xl:col-span-3">Belum ada Dana ZISWAF yang ditetapkan untuk publikasi.</article>@endforelse</div></section>
            <section class="mt-12 rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">Penggunaan dana · Actual</p><h2 class="mt-1 text-2xl font-bold text-emerald-950">Kegiatan dan Realisasi Posted</h2><div class="mt-5 space-y-3">@forelse($report['programs'] as $program)<article class="rounded-xl bg-slate-50 p-4 sm:flex sm:items-center sm:justify-between"><div><p class="font-semibold text-slate-900">{{ $program['name'] }}</p><p class="mt-1 text-sm text-slate-500">{{ collect($program['funding_sources'])->pluck('fund_name')->implode(', ') ?: 'Dana tercatat' }}</p></div><p class="mt-3 font-bold text-rose-700 sm:mt-0 sm:text-right">{{ $rupiah($program['actual_expense']) }}</p></article>@empty<p class="py-6 text-center text-sm text-slate-500">Belum ada penggunaan program yang sudah posted pada periode ini.</p>@endforelse</div></section>
            <section class="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><p class="font-bold">Catatan transparansi</p><p class="mt-2">Angka laporan aktual bersumber dari pembukuan Financial V2. Data program yang belum direalisasikan merupakan rencana internal dan tidak dihitung sebagai pengeluaran aktual maupun dipublikasikan tanpa kebijakan disclosure yang sesuai.</p></section>
            <section class="mt-8 rounded-2xl border border-emerald-100 bg-white p-5"><h2 class="text-2xl font-bold text-emerald-950">Penyaluran kepada penerima manfaat</h2><p class="text-sm text-slate-500 mt-2">Agregat penyaluran yang telah direalisasikan dalam cakupan Dana publik. Nominal merupakan bagian dari realisasi program di atas, bukan pengeluaran tambahan.</p><div class="grid gap-3 sm:grid-cols-2 mt-5">@forelse($report['distributions']['events'] as $event)<article class="bg-slate-50 rounded-xl p-4"><h3 class="font-semibold">{{ $event['program_name'] }} · {{ $event['period'] }}</h3><p class="text-sm text-slate-500 mt-1">{{ $event['from'] }} — {{ $event['through'] }}</p><p class="mt-3">{{ $event['recipient_count'] }} penerima · {{ $rupiah($event['actual_amount']) }}</p></article>@empty<p class="text-sm text-slate-500">Belum ada agregat penyaluran yang dapat dipublikasikan pada periode ini.</p>@endforelse</div><h3 class="font-semibold mt-5">Sebaran penerima</h3><div class="grid gap-2 sm:grid-cols-3 mt-2">@forelse($report['distributions']['regions'] as $region)<p class="rounded-xl bg-slate-50 p-3 text-sm">RT {{ $region['rt'] ?: '—' }} / RW {{ $region['rw'] ?: '—' }}<br><strong>{{ $region['recipient_count'] }} penerima unik</strong></p>@empty<p class="text-sm text-slate-500">Belum ada sebaran wilayah yang dapat dipublikasikan.</p>@endforelse</div></section>
            <footer class="py-10 text-center text-sm text-slate-500">DKM Masjid Raudhotul Jannah · Laporan ZISWAF web read-only</footer>
        </div>
    </main>
@endsection
