@extends('masjid.mrj.admin.financial-v2.layout')

@section('title', 'Detail Saldo Awal')

@section('content')
    @php $tone = match($batch->status) { 'posted' => 'badge-success', 'approved', 'reviewed' => 'badge-warning', default => 'badge-ghost' }; @endphp
    <section class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <div><a class="text-sm text-emerald-700 hover:underline" href="{{ route('financial-v2.opening-balances.index', ['entity' => $entity->id]) }}">← Saldo Awal</a><h1 class="mt-2 text-2xl font-bold">{{ $batch->cutover_reference }}</h1><p class="mt-1 text-sm text-base-content/65">Tanggal posisi rehearsal: {{ $batch->cutover_date->toDateString() }} · Paket bukti: {{ $batch->evidence_package_ref }}</p></div>
        <span class="badge {{ $tone }} badge-lg">{{ str_replace('_', ' ', $batch->status) }}</span>
    </section>

    <section class="mb-6 grid gap-3 sm:grid-cols-3">
        <x-financial-v2.metric label="Total Saldo Awal" value="Rp {{ $summary['totals']['debit'] }}" hint="Debit = Kredit" />
        <x-financial-v2.metric label="Sumber Disetujui" value="Rp {{ $summary['totals']['source_debit'] }}" hint="Dibandingkan per baris" />
        <x-financial-v2.metric label="Selisih" value="Rp {{ $summary['totals']['difference'] }}" hint="Harus Rp 0,00 sebelum persetujuan" />
    </section>

    @if ($batch->status === 'draft')
        <section class="card mb-6 border border-base-300 bg-base-100 shadow-sm"><div class="card-body p-4 sm:p-5"><h2 class="font-bold">Tambah Posisi Sumber</h2><p class="mb-4 text-sm text-base-content/65">Pilih Rekening, Dana, Program jika relevan, sumber data, serta bukti. Pemetaan sumber harus sudah disiapkan dan disetujui secara terpisah.</p>
            <form method="POST" action="{{ route('financial-v2.opening-balances.lines.store', $batch) }}" enctype="multipart/form-data" class="grid gap-3 md:grid-cols-2">@csrf<input type="hidden" name="entity" value="{{ $entity->id }}">
                <label class="form-control"><span class="label-text text-xs font-semibold">Akun</span><select class="select select-bordered select-sm" name="account_id" required><option value="">Pilih akun</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->code }} · {{ $account->name }}</option>@endforeach</select></label>
                <label class="form-control"><span class="label-text text-xs font-semibold">Rekening (bila relevan)</span><select class="select select-bordered select-sm" name="financial_account_id"><option value="">Tidak ada</option>@foreach($financialAccounts as $account)<option value="{{ $account->id }}">{{ $account->code }} · {{ $account->name }}</option>@endforeach</select></label>
                <label class="form-control"><span class="label-text text-xs font-semibold">Dana (bila relevan)</span><select class="select select-bordered select-sm" name="fund_id"><option value="">Tidak ada</option>@foreach($funds as $fund)<option value="{{ $fund->id }}">{{ $fund->code }} · {{ $fund->name }}</option>@endforeach</select></label>
                <label class="form-control"><span class="label-text text-xs font-semibold">Program (bila relevan)</span><select class="select select-bordered select-sm" name="program_id"><option value="">Tidak ada</option>@foreach($programs as $program)<option value="{{ $program->id }}">{{ $program->code }} · {{ $program->name }}</option>@endforeach</select></label>
                <label class="form-control"><span class="label-text text-xs font-semibold">Sumber data</span><input class="input input-bordered input-sm" name="source_reference" placeholder="statement-bank-001" required></label>
                <label class="form-control"><span class="label-text text-xs font-semibold">Referensi bukti</span><input class="input input-bordered input-sm" name="evidence_ref" placeholder="rekening/statement-001" required></label>
                <label class="form-control"><span class="label-text text-xs font-semibold">Lampiran bukti</span><input class="file-input file-input-bordered file-input-sm" type="file" name="evidence" accept=".pdf,.jpg,.jpeg,.png,.webp" required></label>
                <label class="form-control"><span class="label-text text-xs font-semibold">Penjelasan</span><input class="input input-bordered input-sm" name="line_description" placeholder="Contoh: saldo rekening sesuai statement"></label>
                <details class="md:col-span-2 rounded-lg border border-base-300 p-3"><summary class="cursor-pointer text-sm font-semibold">Detail Akuntansi</summary><p class="mt-2 text-xs text-base-content/60">Bagian ini dipakai verifikator untuk memastikan posisi sumber seimbang. Nilai sumber dan nilai V2 harus sama; sistem menolak selisih.</p><div class="mt-3 grid gap-3 sm:grid-cols-2"><label class="form-control"><span class="label-text text-xs">Debit Saldo Awal</span><input class="input input-bordered input-sm" name="debit_amount" value="0" inputmode="decimal" required></label><label class="form-control"><span class="label-text text-xs">Kredit Saldo Awal</span><input class="input input-bordered input-sm" name="credit_amount" value="0" inputmode="decimal" required></label><label class="form-control"><span class="label-text text-xs">Debit dari Sumber</span><input class="input input-bordered input-sm" name="source_debit_amount" value="0" inputmode="decimal" required></label><label class="form-control"><span class="label-text text-xs">Kredit dari Sumber</span><input class="input input-bordered input-sm" name="source_credit_amount" value="0" inputmode="decimal" required></label></div></details>
                <div class="md:col-span-2"><button class="btn btn-primary btn-sm" type="submit">Tambahkan Posisi & Bukti</button></div>
            </form>
        </div></section>
    @endif

    <section class="card mb-6 border border-base-300 bg-base-100 shadow-sm"><div class="card-body p-4 sm:p-5"><div class="mb-3 flex items-center justify-between"><div><h2 class="font-bold">Ringkasan Saldo Awal</h2><p class="text-sm text-base-content/65">Rekening, Dana, Akun, sumber, bukti, status, dan selisih ditampilkan eksplisit.</p></div>@if ($batch->status === 'draft')<form method="POST" action="{{ route('financial-v2.opening-balances.review', $batch) }}">@csrf<input type="hidden" name="entity" value="{{ $entity->id }}"><button class="btn btn-outline btn-sm" type="submit">Verifikasi Saldo Awal</button></form>@elseif($batch->status === 'reviewed')<form method="POST" action="{{ route('financial-v2.opening-balances.approve', $batch) }}">@csrf<input type="hidden" name="entity" value="{{ $entity->id }}"><button class="btn btn-warning btn-sm" type="submit">Setujui</button></form>@elseif($batch->status === 'approved')<form method="POST" action="{{ route('financial-v2.opening-balances.post', $batch) }}">@csrf<input type="hidden" name="entity" value="{{ $entity->id }}"><button class="btn btn-success btn-sm" type="submit">Catat melalui Posting Engine</button></form>@endif</div>
        <div class="overflow-x-auto"><table class="table table-sm"><thead><tr><th>Akun / Rekening / Dana</th><th>Sumber & Bukti</th><th class="text-right">Saldo Awal</th><th class="text-right">Sumber</th><th class="text-right">Selisih</th><th>Status</th></tr></thead><tbody>@forelse($batch->lines as $line)<tr><td><div class="font-medium">{{ $line->account->code }} · {{ $line->account->name }}</div><div class="text-xs opacity-60">{{ $line->financialAccount?->name ?? 'Tanpa rekening' }} · {{ $line->fund?->name ?? 'Tanpa dana' }} · {{ $line->program?->name ?? 'Tanpa program' }}</div></td><td><div>{{ $line->source_reference }}</div><div class="text-xs opacity-60">{{ $line->evidence_ref }}</div></td><td class="text-right font-mono">Rp {{ $line->debit_amount !== '0.00' ? $line->debit_amount : '-'.$line->credit_amount }}</td><td class="text-right font-mono">Rp {{ $line->source_debit_amount !== '0.00' ? $line->source_debit_amount : '-'.$line->source_credit_amount }}</td><td class="text-right font-mono">Rp {{ $line->reconciliation_difference }}</td><td><span class="badge {{ $line->reconciliation_status === 'reconciled' ? 'badge-success' : 'badge-warning' }} badge-sm">{{ $line->reconciliation_status }}</span></td></tr>@empty<tr><td colspan="6" class="text-center text-base-content/60">Belum ada posisi sumber.</td></tr>@endforelse</tbody></table></div>
    </div></section>

    <section class="grid gap-6 lg:grid-cols-3">
        @foreach (['by_account' => 'Per Akun', 'by_financial_account' => 'Per Rekening', 'by_fund' => 'Per Dana'] as $groupKey => $title)
            <div class="card border border-base-300 bg-base-100 shadow-sm"><div class="card-body p-4"><h2 class="font-semibold">{{ $title }}</h2><div class="overflow-x-auto"><table class="table table-sm"><thead><tr><th>Dimensi</th><th class="text-right">Saldo Awal</th><th class="text-right">Sumber</th><th class="text-right">Selisih</th></tr></thead><tbody>@forelse($summary[$groupKey] as $row)<tr><td class="font-mono text-xs">{{ $row[$groupKey === 'by_account' ? 'account_id' : ($groupKey === 'by_fund' ? 'fund_id' : 'financial_account_id')] ?? 'Tidak diatribusikan' }}</td><td class="text-right font-mono">{{ $row['debit'] }}</td><td class="text-right font-mono">{{ $row['source_debit'] }}</td><td class="text-right font-mono">{{ $row['difference'] }}</td></tr>@empty<tr><td colspan="4" class="text-center opacity-60">Belum ada data.</td></tr>@endforelse</tbody></table></div></div></div>
        @endforeach
    </section>
@endsection
