@extends('masjid.mrj.admin.financial-v2.layout')

@section('title', 'Master Dana')

@section('content')
    @include('masjid.mrj.admin.financial-v2.masters._header', [
        'title' => 'Dana',
        'subtitle' => 'Dana menjawab sumber atau peruntukan uang. Dana tidak sama dengan Rekening/Kas, Program, maupun saldo. Saldo resmi hanya berasal dari ledger yang telah diposting.',
    ])

    @if ($entity)
        <section class="grid gap-6 xl:grid-cols-2">
            <form method="post" action="{{ route('financial-v2.masters.funds.store') }}" data-financial-ajax class="rounded-2xl border border-base-300 bg-base-100 p-5 shadow-sm">
                @csrf <input type="hidden" name="entity" value="{{ $entity->id }}">
                <h2 class="text-lg font-bold">Tambah Dana</h2>
                <p class="mt-1 text-sm text-base-content/65">Dana baru selalu draft. Tipe dan pembatasannya perlu kompatibel serta aktif sebelum Dana dapat diaktifkan.</p>
                <div class="mt-5 grid gap-4 sm:grid-cols-2">
                    <label class="form-control"><span class="label-text text-sm">Nama Dana</span><input required name="name" maxlength="160" class="input input-bordered" placeholder="Nama Dana"></label>
                    <label class="form-control"><span class="label-text text-sm">Kode Dana</span><input required name="code" maxlength="40" class="input input-bordered" placeholder="DANA-001"></label>
                    <label class="form-control"><span class="label-text text-sm">Klasifikasi Dana</span><select required name="fund_type_id" class="select select-bordered"><option value="">Pilih klasifikasi</option>@foreach ($fundTypes as $type)<option value="{{ $type->id }}">{{ $type->name }} · {{ str($type->classification)->replace('_', ' ')->title() }}</option>@endforeach</select></label>
                    <label class="form-control"><span class="label-text text-sm">Pembatasan Dana</span><select required name="fund_restriction_id" class="select select-bordered"><option value="">Pilih pembatasan</option>@foreach ($restrictions as $restriction)<option value="{{ $restriction->id }}">{{ $restriction->name }} · {{ ucfirst($restriction->status) }}</option>@endforeach</select></label>
                    <label class="form-control sm:col-span-2"><span class="label-text text-sm">Tujuan / peruntukan</span><textarea required name="purpose_statement" class="textarea textarea-bordered min-h-24" placeholder="Jelaskan peruntukan Dana sesuai kebijakan yang disetujui."></textarea></label>
                    <label class="form-control sm:col-span-2"><span class="label-text text-sm">Penggunaan yang dilarang <span class="text-base-content/45">(opsional)</span></span><textarea name="prohibited_use_statement" class="textarea textarea-bordered min-h-20" placeholder="Gunakan bila kebijakan secara eksplisit melarang penggunaan tertentu."></textarea></label>
                    <label class="form-control"><span class="label-text text-sm">Minimum saldo kebijakan <span class="text-base-content/45">(opsional)</span></span><input name="minimum_balance_policy" inputmode="decimal" class="input input-bordered" placeholder="0.00"></label>
                    <label class="label cursor-pointer justify-start gap-3 pt-8"><input type="checkbox" name="allow_negative_balance" value="1" class="checkbox"><span class="label-text text-sm">Izinkan saldo Dana negatif jika kebijakan memang mengizinkan</span></label>
                    <label class="form-control"><span class="label-text text-sm">Berlaku mulai <span class="text-base-content/45">(opsional)</span></span><input type="date" name="valid_from" class="input input-bordered"></label>
                    <label class="form-control"><span class="label-text text-sm">Berlaku sampai <span class="text-base-content/45">(opsional)</span></span><input type="date" name="valid_to" class="input input-bordered"></label>
                </div>
                <button class="btn btn-primary mt-5">Simpan draft Dana</button>
            </form>

            <section class="rounded-2xl border border-base-300 bg-base-100 shadow-sm">
                <div class="border-b border-base-300 p-5"><h2 class="text-lg font-bold">Daftar Dana</h2><p class="mt-1 text-sm text-base-content/65">Tidak ada Dana bisnis yang di-seed. Seluruh nilai di bawah merupakan konfigurasi yang dibuat pengurus.</p></div>
                <div class="divide-y divide-base-200">
                    @forelse ($funds as $fund)
                        <article class="p-5">
                            <div class="flex flex-wrap items-start justify-between gap-3"><div><p class="font-semibold">{{ $fund->name }}</p><p class="text-sm text-base-content/60">{{ $fund->code }} · {{ $fund->type?->name }} · {{ $fund->restriction?->name }}</p></div><span class="badge {{ $fund->status === 'active' ? 'badge-success' : 'badge-ghost' }}">{{ ucfirst($fund->status) }}</span></div>
                            <p class="mt-3 text-sm leading-6 text-base-content/70">{{ $fund->purpose_statement }}</p>
                            <p class="mt-2 text-xs text-base-content/55">{{ $fund->policyVersions->where('status', 'effective')->count() }} versi kebijakan berlaku · Dana tidak menampilkan atau membentuk saldo di halaman master.</p>
                            <div class="mt-4 flex flex-wrap gap-2">
                                @if ($fund->status !== 'active' && $fund->status !== 'closed')<form method="post" action="{{ route('financial-v2.masters.funds.activate', $fund) }}" data-financial-ajax>@csrf<input type="hidden" name="entity" value="{{ $entity->id }}"><input type="hidden" name="effective_date" value="{{ now()->toDateString() }}"><button class="btn btn-success btn-sm">Aktifkan</button></form>@endif
                                @if ($fund->status === 'active')<form method="post" action="{{ route('financial-v2.masters.funds.deactivate', $fund) }}" data-financial-ajax>@csrf<input type="hidden" name="entity" value="{{ $entity->id }}"><input type="hidden" name="effective_date" value="{{ now()->toDateString() }}"><button class="btn btn-outline btn-sm">Nonaktifkan</button></form>@endif
                            </div>
                            @if ($fund->status !== 'active')
                                <details class="mt-4 rounded-xl bg-base-200 p-4"><summary class="cursor-pointer text-sm font-semibold">Ubah draft</summary>
                                    <form method="post" action="{{ route('financial-v2.masters.funds.update', $fund) }}" data-financial-ajax class="mt-4 grid gap-3 sm:grid-cols-2">@csrf @method('PUT')<input type="hidden" name="entity" value="{{ $entity->id }}">
                                        <input required name="name" value="{{ $fund->name }}" class="input input-bordered input-sm"><input required name="code" value="{{ $fund->code }}" class="input input-bordered input-sm">
                                        <select required name="fund_type_id" class="select select-bordered select-sm">@foreach ($fundTypes as $type)<option value="{{ $type->id }}" @selected($fund->fund_type_id === $type->id)>{{ $type->name }}</option>@endforeach</select><select required name="fund_restriction_id" class="select select-bordered select-sm">@foreach ($restrictions as $restriction)<option value="{{ $restriction->id }}" @selected($fund->fund_restriction_id === $restriction->id)>{{ $restriction->name }}</option>@endforeach</select>
                                        <textarea required name="purpose_statement" class="textarea textarea-bordered textarea-sm sm:col-span-2">{{ $fund->purpose_statement }}</textarea><textarea name="prohibited_use_statement" class="textarea textarea-bordered textarea-sm sm:col-span-2">{{ $fund->prohibited_use_statement }}</textarea>
                                        <input name="minimum_balance_policy" value="{{ $fund->minimum_balance_policy }}" placeholder="Minimum saldo" class="input input-bordered input-sm"><label class="label cursor-pointer justify-start gap-2"><input type="checkbox" name="allow_negative_balance" value="1" class="checkbox checkbox-sm" @checked($fund->allow_negative_balance)><span class="label-text text-sm">Izinkan negatif</span></label>
                                        <input type="date" name="valid_from" value="{{ $fund->valid_from?->toDateString() }}" class="input input-bordered input-sm"><input type="date" name="valid_to" value="{{ $fund->valid_to?->toDateString() }}" class="input input-bordered input-sm"><button class="btn btn-primary btn-sm">Simpan perubahan</button>
                                    </form>
                                </details>
                            @endif
                        </article>
                    @empty <div class="p-8 text-center text-sm text-base-content/60">Belum ada Dana yang dikonfigurasi.</div>
                    @endforelse
                </div>
            </section>
        </section>

        <section class="mt-6 grid gap-6 xl:grid-cols-2">
            <article class="rounded-2xl border border-base-300 bg-base-100 p-5 shadow-sm">
                <h2 class="text-lg font-bold">Klasifikasi Dana</h2>
                <form method="post" action="{{ route('financial-v2.masters.fund-types.store') }}" data-financial-ajax class="mt-4 grid gap-3 sm:grid-cols-2">@csrf<input type="hidden" name="entity" value="{{ $entity->id }}"><input required name="name" class="input input-bordered input-sm" placeholder="Nama klasifikasi"><input required name="code" class="input input-bordered input-sm" placeholder="Kode"><select required name="classification" class="select select-bordered select-sm">@foreach (['unrestricted' => 'Unrestricted', 'designated' => 'Designated', 'restricted' => 'Restricted', 'perpetual_restricted' => 'Perpetual restricted', 'custodial' => 'Custodial', 'syariah' => 'Syariah'] as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select><select required name="status" class="select select-bordered select-sm"><option value="active">Aktif</option><option value="inactive">Tidak aktif</option></select><input type="date" name="valid_from" class="input input-bordered input-sm"><input type="date" name="valid_to" class="input input-bordered input-sm"><button class="btn btn-outline btn-sm sm:col-span-2">Simpan klasifikasi</button></form>
                <div class="mt-5 space-y-2">@forelse ($fundTypes as $type)<details class="rounded-lg bg-base-200 p-3"><summary class="cursor-pointer text-sm font-medium">{{ $type->name }} <span class="text-base-content/55">· {{ str($type->classification)->replace('_', ' ') }}</span></summary><form method="post" action="{{ route('financial-v2.masters.fund-types.update', $type) }}" data-financial-ajax class="mt-3 grid gap-2 sm:grid-cols-2">@csrf @method('PUT')<input type="hidden" name="entity" value="{{ $entity->id }}"><input required name="name" value="{{ $type->name }}" class="input input-bordered input-sm"><input required name="code" value="{{ $type->code }}" class="input input-bordered input-sm"><select required name="classification" class="select select-bordered select-sm">@foreach (['unrestricted','designated','restricted','perpetual_restricted','custodial','syariah'] as $value)<option value="{{ $value }}" @selected($type->classification === $value)>{{ str($value)->replace('_', ' ')->title() }}</option>@endforeach</select><select required name="status" class="select select-bordered select-sm"><option value="active" @selected($type->status === 'active')>Aktif</option><option value="inactive" @selected($type->status === 'inactive')>Tidak aktif</option></select><input type="date" name="valid_from" value="{{ optional($type->valid_from)->toDateString() }}" class="input input-bordered input-sm"><input type="date" name="valid_to" value="{{ optional($type->valid_to)->toDateString() }}" class="input input-bordered input-sm"><button class="btn btn-ghost btn-sm">Simpan</button></form></details>@empty <p class="text-sm text-base-content/60">Belum ada klasifikasi.</p>@endforelse</div>
            </article>

            <article class="rounded-2xl border border-base-300 bg-base-100 p-5 shadow-sm">
                <h2 class="text-lg font-bold">Pembatasan Dana</h2>
                <form method="post" action="{{ route('financial-v2.masters.restrictions.store') }}" data-financial-ajax class="mt-4 grid gap-3 sm:grid-cols-2">@csrf<input type="hidden" name="entity" value="{{ $entity->id }}"><select required name="fund_type_id" class="select select-bordered select-sm"><option value="">Klasifikasi</option>@foreach ($fundTypes as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select><input required name="name" class="input input-bordered input-sm" placeholder="Nama pembatasan"><input required name="code" class="input input-bordered input-sm" placeholder="Kode"><select required name="severity" class="select select-bordered select-sm"><option value="low">Rendah</option><option value="medium">Sedang</option><option value="high">Tinggi</option><option value="critical">Kritis</option></select><textarea required name="policy_basis" class="textarea textarea-bordered textarea-sm sm:col-span-2" placeholder="Dasar kebijakan"></textarea><select required name="status" class="select select-bordered select-sm"><option value="draft">Draft</option><option value="active">Aktif</option><option value="retired">Pensiun</option></select><span></span><input type="date" name="valid_from" class="input input-bordered input-sm"><input type="date" name="valid_to" class="input input-bordered input-sm"><button class="btn btn-outline btn-sm sm:col-span-2">Simpan pembatasan</button></form>
                <div class="mt-5 space-y-2">@forelse ($restrictions as $restriction)<details class="rounded-lg bg-base-200 p-3"><summary class="cursor-pointer text-sm font-medium">{{ $restriction->name }} <span class="text-base-content/55">· {{ ucfirst($restriction->severity) }} · {{ ucfirst($restriction->status) }}</span></summary><form method="post" action="{{ route('financial-v2.masters.restrictions.update', $restriction) }}" data-financial-ajax class="mt-3 grid gap-2 sm:grid-cols-2">@csrf @method('PUT')<input type="hidden" name="entity" value="{{ $entity->id }}"><select required name="fund_type_id" class="select select-bordered select-sm">@foreach ($fundTypes as $type)<option value="{{ $type->id }}" @selected($restriction->fund_type_id === $type->id)>{{ $type->name }}</option>@endforeach</select><input required name="name" value="{{ $restriction->name }}" class="input input-bordered input-sm"><input required name="code" value="{{ $restriction->code }}" class="input input-bordered input-sm"><select required name="severity" class="select select-bordered select-sm">@foreach (['low','medium','high','critical'] as $value)<option value="{{ $value }}" @selected($restriction->severity === $value)>{{ ucfirst($value) }}</option>@endforeach</select><textarea required name="policy_basis" class="textarea textarea-bordered textarea-sm sm:col-span-2">{{ $restriction->policy_basis }}</textarea><select required name="status" class="select select-bordered select-sm">@foreach (['draft','active','retired'] as $value)<option value="{{ $value }}" @selected($restriction->status === $value)>{{ ucfirst($value) }}</option>@endforeach</select><span></span><input type="date" name="valid_from" value="{{ optional($restriction->valid_from)->toDateString() }}" class="input input-bordered input-sm"><input type="date" name="valid_to" value="{{ optional($restriction->valid_to)->toDateString() }}" class="input input-bordered input-sm"><button class="btn btn-ghost btn-sm">Simpan</button></form></details>@empty <p class="text-sm text-base-content/60">Belum ada pembatasan.</p>@endforelse</div>
            </article>
        </section>
    @endif
@endsection
