@extends('masjid.mrj.admin.financial-v2.layout')

@section('title', 'Aturan Dana')

@section('content')
    @include('masjid.mrj.admin.financial-v2.masters._header', [
        'title' => 'Aturan Dana',
        'subtitle' => 'Aturan Dana menentukan apakah Dana dapat digunakan untuk suatu jenis transaksi, kategori, atau Program. Pemeriksaan tetap dilakukan di server saat transaksi diproses; halaman ini hanya mengelola konfigurasi versi kebijakan.',
    ])

    @if ($entity)
        <section class="grid gap-6 xl:grid-cols-[minmax(0,0.9fr)_minmax(0,1.35fr)]">
            <form method="post" action="{{ route('financial-v2.masters.policies.store') }}" data-financial-ajax class="rounded-2xl border border-base-300 bg-base-100 p-5 shadow-sm">
                @csrf <input type="hidden" name="entity" value="{{ $entity->id }}">
                <h2 class="text-lg font-bold">Versi Aturan Dana Baru</h2>
                <p class="mt-1 text-sm text-base-content/65">Kebijakan yang sudah berlaku bersifat tetap. Buat versi baru untuk perubahan pada periode berikutnya.</p>
                <div class="mt-5 grid gap-4">
                    <label class="form-control"><span class="label-text text-sm">Dana</span><select required name="fund_id" class="select select-bordered"><option value="">Pilih Dana</option>@foreach ($funds as $fund)<option value="{{ $fund->id }}">{{ $fund->name }} · {{ ucfirst($fund->status) }}</option>@endforeach</select></label>
                    <div class="grid gap-4 sm:grid-cols-2"><label class="form-control"><span class="label-text text-sm">Berlaku mulai</span><input required type="date" name="effective_from" value="{{ now()->toDateString() }}" class="input input-bordered"></label><label class="form-control"><span class="label-text text-sm">Berlaku sampai <span class="text-base-content/45">(opsional)</span></span><input type="date" name="effective_to" class="input input-bordered"></label></div>
                    <label class="form-control"><span class="label-text text-sm">Referensi dokumen kebijakan</span><input required name="policy_document_ref" maxlength="500" class="input input-bordered" placeholder="Nomor atau lokasi dokumen yang disetujui"></label>
                    <label class="form-control"><span class="label-text text-sm">Referensi matriks yang diizinkan <span class="text-base-content/45">(wajib untuk Dana restricted)</span></span><input name="allowed_matrix_ref" maxlength="500" class="input input-bordered" placeholder="Referensi matriks persetujuan"></label>
                    <label class="form-control"><span class="label-text text-sm">Tingkat persetujuan pengecualian</span><input required name="exception_approval_level" maxlength="80" class="input input-bordered" placeholder="Sesuai kebijakan internal"></label>
                </div>
                <button class="btn btn-primary mt-5">Simpan draft kebijakan</button>
            </form>

            <section class="rounded-2xl border border-base-300 bg-base-100 shadow-sm">
                <div class="border-b border-base-300 p-5"><h2 class="text-lg font-bold">Versi dan Aturan yang Dikonfigurasi</h2><p class="mt-1 text-sm text-base-content/65">Tidak ada kelayakan Program–Dana yang dihardcode. Aturan di bawah menjadi sumber konfigurasi untuk validasi server-side.</p></div>
                <div class="divide-y divide-base-200">
                    @forelse ($versions as $version)
                        <article class="p-5">
                            <div class="flex flex-wrap items-start justify-between gap-3"><div><p class="font-semibold">{{ $version->fund?->name }}</p><p class="text-sm text-base-content/60">Versi {{ $version->version_no }} · {{ $version->effective_from?->translatedFormat('d M Y') }}@if($version->effective_to) — {{ $version->effective_to->translatedFormat('d M Y') }}@endif</p></div><span class="badge {{ $version->status === 'effective' ? 'badge-success' : 'badge-ghost' }}">{{ $version->status === 'effective' ? 'Berlaku' : ucfirst($version->status) }}</span></div>
                            <p class="mt-3 text-sm text-base-content/65">Dokumen: {{ $version->policy_document_ref }}@if($version->allowed_matrix_ref) · Matriks: {{ $version->allowed_matrix_ref }}@endif</p>
                            @if ($version->status === 'draft')
                                <div class="mt-4 flex flex-wrap gap-2"><form method="post" action="{{ route('financial-v2.masters.policies.effective', $version) }}" data-financial-ajax>@csrf<input type="hidden" name="entity" value="{{ $entity->id }}"><button class="btn btn-success btn-sm">Berlakukan versi</button></form></div>
                                <details class="mt-4 rounded-xl bg-base-200 p-4"><summary class="cursor-pointer text-sm font-semibold">Ubah draft kebijakan</summary><form method="post" action="{{ route('financial-v2.masters.policies.update', $version) }}" data-financial-ajax class="mt-4 grid gap-3 sm:grid-cols-2">@csrf @method('PUT')<input type="hidden" name="entity" value="{{ $entity->id }}"><input required type="date" name="effective_from" value="{{ $version->effective_from?->toDateString() }}" class="input input-bordered input-sm"><input type="date" name="effective_to" value="{{ $version->effective_to?->toDateString() }}" class="input input-bordered input-sm"><input required name="policy_document_ref" value="{{ $version->policy_document_ref }}" class="input input-bordered input-sm sm:col-span-2"><input name="allowed_matrix_ref" value="{{ $version->allowed_matrix_ref }}" placeholder="Referensi matriks" class="input input-bordered input-sm"><input required name="exception_approval_level" value="{{ $version->exception_approval_level }}" class="input input-bordered input-sm"><button class="btn btn-primary btn-sm">Simpan perubahan</button></form></details>
                            @endif

                            <div class="mt-5 rounded-xl border border-base-300 p-4"><p class="text-sm font-semibold">Aturan penggunaan</p><p class="mt-1 text-xs leading-5 text-base-content/60">Kosong pada kategori atau Program berarti aturan berlaku umum untuk jenis transaksi itu. Tambahkan aturan spesifik hanya bila disetujui kebijakan.</p>
                                <div class="mt-3 space-y-2">@forelse ($version->rules as $rule)<div class="rounded-lg bg-base-200 p-3 text-sm"><div class="flex flex-wrap justify-between gap-2"><span>{{ $transactionTypes->firstWhere('id', $rule->transaction_type_id)?->name ?? 'Jenis transaksi' }} · {{ $rule->decision === 'allowed' ? 'Diizinkan' : 'Dilarang' }}</span><span class="text-base-content/55">{{ $categories->firstWhere('id', $rule->category_id)?->name ?? 'Semua kategori' }} · {{ $programs->firstWhere('id', $rule->program_id)?->name ?? 'Semua Program' }}</span></div>@if($rule->rationale)<p class="mt-1 text-xs text-base-content/65">{{ $rule->rationale }}</p>@endif
                                    @if($version->status === 'draft')<details class="mt-3"><summary class="cursor-pointer text-xs font-semibold">Ubah aturan</summary><form method="post" action="{{ route('financial-v2.masters.policy-rules.update', $rule) }}" data-financial-ajax class="mt-3 grid gap-2 sm:grid-cols-2">@csrf @method('PUT')<input type="hidden" name="entity" value="{{ $entity->id }}"><select required name="transaction_type_id" class="select select-bordered select-xs">@foreach ($transactionTypes as $type)<option value="{{ $type->id }}" @selected($rule->transaction_type_id === $type->id)>{{ $type->name }}</option>@endforeach</select><select required name="decision" class="select select-bordered select-xs"><option value="allowed" @selected($rule->decision === 'allowed')>Diizinkan</option><option value="prohibited" @selected($rule->decision === 'prohibited')>Dilarang</option></select><select name="account_id" class="select select-bordered select-xs"><option value="">Semua akun</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected($rule->account_id === $account->id)>{{ $account->name }}</option>@endforeach</select><select name="category_id" class="select select-bordered select-xs"><option value="">Semua kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($rule->category_id === $category->id)>{{ $category->name }}</option>@endforeach</select><select name="program_id" class="select select-bordered select-xs"><option value="">Semua Program</option>@foreach($programs as $program)<option value="{{ $program->id }}" @selected($rule->program_id === $program->id)>{{ $program->name }}</option>@endforeach</select><input name="rationale" value="{{ $rule->rationale }}" placeholder="Dasar aturan" class="input input-bordered input-xs"><button class="btn btn-ghost btn-xs">Simpan</button></form></details>@endif
                                </div>@empty <p class="text-sm text-base-content/60">Belum ada aturan pada versi ini.</p>@endforelse</div>
                                @if ($version->status === 'draft')<details class="mt-4"><summary class="cursor-pointer text-sm font-semibold text-emerald-800">+ Tambah aturan penggunaan</summary><form method="post" action="{{ route('financial-v2.masters.policy-rules.store', $version) }}" data-financial-ajax class="mt-3 grid gap-3 sm:grid-cols-2">@csrf<input type="hidden" name="entity" value="{{ $entity->id }}"><select required name="transaction_type_id" class="select select-bordered select-sm"><option value="">Jenis transaksi</option>@foreach($transactionTypes as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select><select required name="decision" class="select select-bordered select-sm"><option value="allowed">Diizinkan</option><option value="prohibited">Dilarang</option></select><select name="account_id" class="select select-bordered select-sm"><option value="">Semua akun</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->code }} — {{ $account->name }}</option>@endforeach</select><select name="category_id" class="select select-bordered select-sm"><option value="">Semua kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select><select name="program_id" class="select select-bordered select-sm"><option value="">Semua Program</option>@foreach($programs as $program)<option value="{{ $program->id }}">{{ $program->name }}</option>@endforeach</select><input name="rationale" class="input input-bordered input-sm" placeholder="Dasar aturan"><button class="btn btn-outline btn-sm sm:col-span-2">Simpan aturan</button></form></details>@endif
                            </div>
                        </article>
                    @empty <div class="p-8 text-center text-sm text-base-content/60">Belum ada versi Aturan Dana yang dikonfigurasi.</div>
                    @endforelse
                </div>
            </section>
        </section>
    @endif
@endsection
