@extends('masjid.mrj.admin.financial-v2.layout')

@section('title', 'Detail Program ZISWAF V2')

@php $rupiah = static fn (string $amount): string => 'Rp'.number_format((float) $amount, 0, ',', '.'); $program = $report['program']; @endphp

@section('content')
    <a class="btn btn-ghost btn-sm mb-4" href="{{ route('financial-v2.ziswaf-v2.index', ['entity' => $entity?->id, 'from' => $filters['from'], 'through' => $filters['through']]) }}">← Kembali ke laporan ZISWAF V2</a>
    <section class="mb-6 rounded-3xl bg-emerald-950 p-6 text-white sm:p-8"><span class="badge badge-outline border-emerald-300 text-emerald-100">PROGRAM DETAIL</span><h1 class="mt-3 text-3xl font-bold">{{ $program['name'] }}</h1><p class="mt-2 text-emerald-100/80">{{ $program['code'] }} · Periode laporan {{ $report['period']['from'] }} — {{ $report['period']['through'] }}</p></section>
    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><x-financial-v2.metric title="Anggaran · Plan" :value="$rupiah($program['budget'])" tone="warning" /><x-financial-v2.metric title="Alokasi · Plan" :value="$rupiah($program['allocation'])" tone="warning" /><x-financial-v2.metric title="Realisasi · Posted link" :value="$rupiah($program['realization'])" /><x-financial-v2.metric title="Actual Expense" :value="$rupiah($program['actual_expense'])" tone="success" /><x-financial-v2.metric title="Sisa alokasi" :value="$rupiah($program['remaining'])" /></section>
    <section class="mt-8 grid gap-6 xl:grid-cols-2"><x-financial-v2.table title="Funding Sources" class="hidden md:block"><thead><tr><th>Dana</th><th class="text-right">Allocated · PLAN</th><th class="text-right">Realized · ACTUAL</th></tr></thead><tbody>@forelse($program['funding_sources'] as $source)<tr><td>{{ $source['fund_name'] }}<div class="text-xs opacity-60">{{ $source['fund_code'] }}</div></td><td class="text-right font-mono text-amber-700">{{ $rupiah($source['allocated']) }}</td><td class="text-right font-mono text-emerald-700">{{ $rupiah($source['realized']) }}</td></tr>@empty<tr><td colspan="3" class="py-8 text-center text-base-content/60">Belum ada sumber pendanaan.</td></tr>@endforelse</tbody></x-financial-v2.table><article class="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950"><p class="font-bold">Batas data</p><p class="mt-2 leading-6">Alokasi adalah rencana dan tidak mengubah saldo Dana. Actual Expense hanya mengikuti Journal/Ledger Financial V2 yang berstatus posted; draft dan alokasi yang dibatalkan tidak dihitung.</p></article></section>
    <section class="mt-5 space-y-3 md:hidden"><h2 class="font-semibold">Funding Sources</h2>@forelse($program['funding_sources'] as $source)<article class="rounded-2xl border border-base-300 bg-base-100 p-4 shadow-sm"><p class="font-semibold">{{ $source['fund_name'] }}</p><dl class="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt class="opacity-60">Allocated · Plan</dt><dd class="font-mono text-amber-700">{{ $rupiah($source['allocated']) }}</dd></div><div><dt class="opacity-60">Realized · Actual</dt><dd class="font-mono text-emerald-700">{{ $rupiah($source['realized']) }}</dd></div></dl></article>@empty<p class="rounded-2xl bg-base-100 p-4 text-sm opacity-60">Belum ada sumber pendanaan.</p>@endforelse</section>
    <x-financial-v2.table title="Transaction History · POSTED" class="mt-8 hidden md:block"><thead><tr><th>Tanggal</th><th>Keterangan</th><th>Dana</th><th>Kategori</th><th class="text-right">Masuk</th><th class="text-right">Keluar</th></tr></thead><tbody>@forelse($report['transactions'] as $transaction)<tr><td>{{ $transaction['date'] }}</td><td><a class="hover:underline" href="{{ route('financial-v2.transactions.show', $transaction['transaction_id']) }}">{{ $transaction['description'] ?: 'Transaksi Financial V2' }}</a></td><td>{{ $transaction['fund'] }}</td><td>{{ $transaction['category'] }}</td><td class="text-right font-mono text-emerald-700">{{ $transaction['in'] === '0.00' ? '—' : $rupiah($transaction['in']) }}</td><td class="text-right font-mono text-rose-700">{{ $transaction['out'] === '0.00' ? '—' : $rupiah($transaction['out']) }}</td></tr>@empty<tr><td colspan="6" class="py-8 text-center text-base-content/60">Belum ada transaksi posted yang terkait program ini.</td></tr>@endforelse</tbody></x-financial-v2.table>
    <section class="mt-8 space-y-3 md:hidden"><h2 class="font-semibold">Transaction History · POSTED</h2>@forelse($report['transactions'] as $transaction)<article class="rounded-2xl border border-base-300 bg-base-100 p-4 shadow-sm"><a class="font-semibold text-emerald-800" href="{{ route('financial-v2.transactions.show', $transaction['transaction_id']) }}">{{ $transaction['description'] ?: 'Transaksi Financial V2' }}</a><p class="mt-1 text-xs opacity-60">{{ $transaction['date'] }} · {{ $transaction['fund'] }}</p><p class="mt-3 text-sm">{{ $transaction['category'] }}</p><div class="mt-3 flex justify-between font-mono text-sm"><span class="text-emerald-700">{{ $transaction['in'] === '0.00' ? '—' : '+'.$rupiah($transaction['in']) }}</span><span class="text-rose-700">{{ $transaction['out'] === '0.00' ? '—' : '−'.$rupiah($transaction['out']) }}</span></div></article>@empty<p class="rounded-2xl bg-base-100 p-4 text-sm opacity-60">Belum ada transaksi posted yang terkait program ini.</p>@endforelse</section>
    @if($report && $entity)
        @include('masjid.mrj.admin.financial-v2.distributions.report')
    @endif
@endsection
